CREATE USER IF NOT EXISTS carlos;
DROP DATABASE IF EXISTS DB CASCADE;
CREATE DATABASE DB;
GRANT ALL ON DATABASE DB TO carlos;


CREATE TABLE DB.Domain
(
Address VARCHAR(255) PRIMARY KEY,
IsDown BOOL,
Logo VARCHAR(255),
SSLGrade VARCHAR(255),
Title VARCHAR(255),
LastUpdate TIMESTAMPTZ
);

CREATE TABLE DB.Server
(
Address VARCHAR(255) PRIMARY KEY,
Country VARCHAR(255),
DomainAddress VARCHAR(255),
Owner VARCHAR(255),
SSLGrade VARCHAR(255),
LastUpdate TIMESTAMPTZ
);

CREATE TABLE DB.Origin
(
Address VARCHAR(255) PRIMARY KEY,
MetaData VARCHAR(255),
LastUpdate TIMESTAMPTZ
);

CREATE TABLE DB.Connection
(
Id SERIAL PRIMARY KEY,
OriginIP VARCHAR(255),
DomainAddress VARCHAR(255),
LastUpdate TIMESTAMPTZ
);

ALTER TABLE DB.Server ADD CONSTRAINT domain_fk FOREIGN KEY (DomainAddress) REFERENCES DB.Domain (Address) ON DELETE CASCADE;
ALTER TABLE DB.Connection ADD CONSTRAINT connection_fk1 FOREIGN KEY (OriginIP) REFERENCES DB.Origin(Address) ON DELETE CASCADE;
ALTER TABLE DB.Connection ADD CONSTRAINT connection_fk2 FOREIGN KEY (DomainAddress) REFERENCES DB.Domain (Address) ON DELETE CASCADE;
